#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"
ENV_FILE="$REPO_DIR/.env"
ADMIN_TAILNET_PORT=22222
SSH_DROPIN=/etc/ssh/sshd_config.d/00-fyke-loopback.conf
BACKUP_DIR=""

as_root() {
  if (( EUID == 0 )); then
    "$@"
  else
    sudo "$@"
  fi
}

die() {
  printf '\n  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

valid_ipv4() {
  local address="$1" octet
  local -a octets
  [[ "$address" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  IFS=. read -r -a octets <<<"$address"
  for octet in "${octets[@]}"; do
    (( 10#$octet <= 255 )) || return 1
  done
}

reload_ssh_listener() {
  as_root systemctl daemon-reload
  if as_root systemctl is-active --quiet ssh.socket || as_root systemctl is-enabled --quiet ssh.socket; then
    as_root systemctl restart ssh.socket
  else
    as_root systemctl reload ssh.service
  fi
}

loopback_ssh_only() {
  local address endpoint listeners port sshd_effective
  local saw_ipv4=0 saw_ipv6=0

  sshd_effective=$(as_root /usr/sbin/sshd -T) || return 1
  while IFS= read -r port; do
    [[ "$port" == 22 ]] || return 1
  done < <(awk '$1 == "port" {print $2}' <<<"$sshd_effective")
  while IFS= read -r address; do
    case "$address" in
      127.0.0.1:22) saw_ipv4=1 ;;
      '[::1]:22') saw_ipv6=1 ;;
      *) return 1 ;;
    esac
  done < <(awk '$1 == "listenaddress" {print $2}' <<<"$sshd_effective")
  (( saw_ipv4 == 1 && saw_ipv6 == 1 )) || return 1

  listeners=$(as_root ss -H -ltn 'sport = :22')
  [[ -n "$listeners" ]] || return 1
  while IFS= read -r line; do
    endpoint=$(awk '{print $4}' <<<"$line")
    case "$endpoint" in
      127.0.0.1:22|'[::1]:22') ;;
      *) return 1 ;;
    esac
  done <<<"$listeners"
}

restore_ssh_dropin() {
  if [[ -f "$BACKUP_DIR/ssh-dropin.before" ]]; then
    as_root install -o root -g root -m 600 "$BACKUP_DIR/ssh-dropin.before" "$SSH_DROPIN"
  else
    as_root rm -f "$SSH_DROPIN"
  fi
  as_root /usr/sbin/sshd -t
  reload_ssh_listener
}

banner "Fyke live cutover"

stage "Preflight and deployment values"
say "This must run on the Fyke VPS from a shell that can use sudo."
warn "Keep this shell open until every verification stage passes. A provider console is the safest fallback."
for command in docker tailscale ip ss ssh curl systemctl; do
  command -v "$command" >/dev/null 2>&1 || die "required command is missing: $command"
done
if (( EUID != 0 )); then
  command -v sudo >/dev/null 2>&1 || die "required command is missing: sudo"
fi
[[ -x /usr/sbin/sshd ]] || die "OpenSSH server is not installed at /usr/sbin/sshd"
docker info >/dev/null 2>&1 || die "Docker is unavailable to this operator"
as_root true || die "sudo/root access is required"
as_root tailscale status >/dev/null 2>&1 || die "Tailscale is not connected"
if [[ -z "${SSH_CONNECTION:-}" ]]; then
  warn "This does not appear to be an SSH session; make sure a provider console remains available."
fi
say "IPv4 addresses assigned to this VPS:"
ip -4 -brief address show scope global | sed 's/^/    /'
ask FYKE_BIND_IP "Public-facing host IPv4 to bind Fyke sensors to:"
valid_ipv4 "$FYKE_BIND_IP" || die "that is not a valid IPv4 address"
ip -4 address show | grep -Fqw "$FYKE_BIND_IP" || die "$FYKE_BIND_IP is not assigned to a host interface"
[[ "$FYKE_BIND_IP" != 0.0.0.0 && "$FYKE_BIND_IP" != 127.0.0.1 ]] || die "choose the public-facing interface address, not wildcard or loopback"
ask FYKE_ADMIN_USER "Real OpenSSH username (Enter uses $(id -un)):"
FYKE_ADMIN_USER="${FYKE_ADMIN_USER:-$(id -un)}"
detected_dns=$(as_root tailscale status --json 2>/dev/null | sed -n 's/^[[:space:]]*"DNSName": "\([^"]*\)".*/\1/p' | head -n1)
detected_dns="${detected_dns%.}"
ask FYKE_TAILNET_HOST "VPS MagicDNS name (Enter uses ${detected_dns:-the current host}):"
FYKE_TAILNET_HOST="${FYKE_TAILNET_HOST:-$detected_dns}"
[[ -n "$FYKE_TAILNET_HOST" ]] || die "a MagicDNS name is required"
ask TAILSCALE_ADMIN_PRINCIPAL "Tailscale user email or group allowed to administer Fyke:"
[[ -n "$TAILSCALE_ADMIN_PRINCIPAL" ]] || die "an administrator principal is required"
note "No password, SSH key, or Tailscale credential is collected or written."
pause "Values accepted. Press Enter to continue."

stage "Back up the current access configuration"
say "The backup contains SSH configuration, the current .env, and Tailscale Serve status."
confirm "Create a root-only cutover backup now?" || die "stopped before making changes"
BACKUP_DIR="/var/backups/fyke-cutover-$(date -u +%Y%m%dT%H%M%SZ)"
as_root install -d -o root -g root -m 700 "$BACKUP_DIR"
as_root cp -a /etc/ssh/sshd_config "$BACKUP_DIR/sshd_config"
as_root cp -a /etc/ssh/sshd_config.d "$BACKUP_DIR/sshd_config.d"
if as_root test -f "$SSH_DROPIN"; then
  as_root cp -a "$SSH_DROPIN" "$BACKUP_DIR/ssh-dropin.before"
fi
if [[ -f "$ENV_FILE" ]]; then
  as_root cp -a "$ENV_FILE" "$BACKUP_DIR/fyke.env.before"
fi
status_file=$(mktemp)
as_root tailscale serve status --json >"$status_file" 2>/dev/null || as_root tailscale serve status >"$status_file"
as_root install -o root -g root -m 600 "$status_file" "$BACKUP_DIR/tailscale-serve.before"
rm -f "$status_file"
services_file=$(mktemp)
systemctl is-active ssh.service ssh.socket tailscaled.service >"$services_file" 2>&1 || true
as_root install -o root -g root -m 600 "$services_file" "$BACKUP_DIR/services.before"
rm -f "$services_file"
say "Backup created: $BACKUP_DIR"
warn "Do not delete it until the VPS has rebooted successfully and both private paths still work."
pause "Press Enter to continue."

stage "Restrict access in the tailnet policy"
TAILSCALE_IP=$(as_root tailscale ip -4 | head -n1)
say "Tailscale grants are additive. A broad existing allow rule must also be narrowed if only administrators should connect."
open_url "https://login.tailscale.com/admin/acls"
step "Open Access controls and merge this grant into the existing policy; do not replace unrelated rules:"
printf '\n    {\n      "src": ["%s"],\n      "dst": ["%s"],\n      "ip": ["tcp:%s", "tcp:443"]\n    }\n\n' \
  "$TAILSCALE_ADMIN_PRINCIPAL" "$TAILSCALE_IP" "$ADMIN_TAILNET_PORT"
step "Check for broader grants or ACLs that already allow other users to this VPS on those ports. Narrow them if needed."
step "Use the policy editor's tests/preview, then save the policy."
confirm "Is the policy saved and does it permit your administrator identity?" || die "stopped before changing listeners"

stage "Create the private SSH and dashboard paths"
say "Tailscale Serve will proxy private TCP $ADMIN_TAILNET_PORT to loopback OpenSSH and private HTTPS to the loopback dashboard."
confirm "Add both Tailscale Serve endpoints?" || die "stopped before changing Tailscale Serve"
as_root tailscale serve --bg --tcp="$ADMIN_TAILNET_PORT" tcp://127.0.0.1:22
as_root tailscale serve --bg --https=443 http://127.0.0.1:9080
as_root tailscale serve status
curl -fsS http://127.0.0.1:9080/api/v1/health >/dev/null || die "the local Fyke dashboard health endpoint is unavailable"
pause "Private endpoints are configured. Press Enter to verify them from another device."

stage "Verify from a second tailnet terminal"
warn "Do not continue until the following SSH command opens a new, working real shell."
say "From another permitted tailnet device, run:"
printf '\n    ssh -p %s %s@%s\n\n' "$ADMIN_TAILNET_PORT" "$FYKE_ADMIN_USER" "$FYKE_TAILNET_HOST"
say "Then open this dashboard URL in a browser:"
printf '\n    https://%s/\n\n' "$FYKE_TAILNET_HOST"
step "In the new SSH shell, run hostname and id to prove it is real OpenSSH, not the Fyke emulator."
step "Keep both the original shell and the new port-$ADMIN_TAILNET_PORT shell open."
confirm "Do both private paths work from the second tailnet device?" || die "stopped; public OpenSSH remains unchanged"

stage "Restrict real OpenSSH to loopback"
say "This frees the public-facing address on port 22 while keeping OpenSSH reachable through Tailscale Serve."
warn "Ubuntu may use ssh.socket; the wizard validates sshd_config and reloads the active mechanism."
say "Existing explicit SSH listener directives, for review:"
as_root grep -RHE '^[[:space:]]*(Port|ListenAddress)[[:space:]]' /etc/ssh/sshd_config /etc/ssh/sshd_config.d 2>/dev/null | sed 's/^/    /' || true
confirm "Restrict OpenSSH to 127.0.0.1:22 and [::1]:22 now?" || die "stopped before changing OpenSSH"
ssh_dropin_tmp=$(mktemp)
printf '%s\n' \
  '# Managed by Fyke scripts/go-live.sh.' \
  'Port 22' \
  'ListenAddress 127.0.0.1:22' \
  'ListenAddress [::1]:22' >"$ssh_dropin_tmp"
as_root install -o root -g root -m 600 "$ssh_dropin_tmp" "$SSH_DROPIN"
rm -f "$ssh_dropin_tmp"
if ! as_root /usr/sbin/sshd -t; then
  restore_ssh_dropin
  die "sshd rejected the loopback configuration; the previous listener was restored"
fi
if ! reload_ssh_listener; then
  warn "OpenSSH failed to reload with the loopback listener; restoring the previous configuration."
  restore_ssh_dropin || true
  die "OpenSSH reload failed and the wizard attempted an immediate rollback"
fi
if ! loopback_ssh_only; then
  warn "Port 22 is not loopback-only; restoring the prior SSH configuration."
  restore_ssh_dropin
  die "OpenSSH listener validation failed; review other Port/ListenAddress directives"
fi
as_root ss -ltnp 'sport = :22' || true
warn "Use the already-open second terminal to test port $ADMIN_TAILNET_PORT again before continuing."
confirm "Does real SSH still work through Tailscale on port $ADMIN_TAILNET_PORT?" || {
  restore_ssh_dropin
  die "the prior SSH listener was restored"
}

stage "Retire the old Tailscale endpoints"
say "The new private paths are verified, so the port-22 Tailscale SSH interceptor and HTTP dashboard on 9080 can be removed."
confirm "Disable Tailscale SSH on port 22 and the old HTTP Serve endpoint on 9080?" || die "stopped; new private paths remain available"
as_root tailscale set --ssh=false
if ! as_root tailscale serve --http=9080 off; then
  warn "No matching HTTP Serve endpoint on 9080 was removed; review tailscale serve status manually."
fi
as_root tailscale serve status
warn "Retest SSH port $ADMIN_TAILNET_PORT and dashboard HTTPS one more time."
confirm "Are both replacement paths still working?" || die "stop here and use $BACKUP_DIR to restore the prior configuration"

stage "Publish Fyke on the live public ports"
say "Only the selected public-facing IPv4 will receive the honeypot ports; Tailscale and loopback addresses remain separate."
printf '  Bind address: %s\n  Fyke ports:   22, 23, 80, 443\n' "$FYKE_BIND_IP"
confirm "Write the live bindings to .env and recreate the Fyke services?" || die "stopped before publishing live ports"
write_env FYKE_BIND_IP "$FYKE_BIND_IP"
write_env FYKE_SSH_PORT 22
write_env FYKE_TELNET_PORT 23
write_env FYKE_HTTP_PORT 80
write_env FYKE_HTTPS_PORT 443
./deploy.sh
docker compose ps
pause "Fyke is healthy on the live ports. Press Enter to review containment."

stage "Apply containment and provider firewall policy"
say "Fyke's nftables policy blocks sensor-originated forwarding while preserving controller ingestion."
./deploy.sh firewall
confirm "Apply the displayed Fyke sensor-egress policy?" || die "stopped before applying containment; the live sensors remain running"
./deploy.sh firewall apply
ask CLOUD_FIREWALL_URL "Cloud-provider firewall page URL (optional):"
if [[ -n "$CLOUD_FIREWALL_URL" ]]; then
  open_url "$CLOUD_FIREWALL_URL"
fi
step "Allow public inbound TCP 22, 23, 80, and 443 to this VPS."
step "Do not allow public TCP 2222, 2323, 8080, 8443, 9080, or $ADMIN_TAILNET_PORT."
step "Preserve the rules Tailscale already needs; do not disable established traffic or outbound connectivity."
warn "The explicit IPv4 bind does not publish Fyke over IPv6. Keep unsolicited IPv6 inbound closed unless you deliberately add and test IPv6 sensor bindings."
confirm "Is the provider firewall saved without removing your Tailscale path?" || die "review the provider firewall before closing this shell"

stage "Verify the cutover and retain rollback data"
say "From a non-tailnet external machine, verify public Fyke:"
printf '\n    ssh -p 22 deploy@%s\n    curl -i http://%s/\n    curl -ki https://%s/\n\n' \
  "$FYKE_BIND_IP" "$FYKE_BIND_IP" "$FYKE_BIND_IP"
say "From a permitted tailnet device, verify private administration:"
printf '\n    ssh -p %s %s@%s\n    https://%s/\n\n' \
  "$ADMIN_TAILNET_PORT" "$FYKE_ADMIN_USER" "$FYKE_TAILNET_HOST" "$FYKE_TAILNET_HOST"
step "Confirm public TCP 9080 and $ADMIN_TAILNET_PORT fail from outside the tailnet."
step "Confirm public port 22 shows the Fyke banner, while tailnet port $ADMIN_TAILNET_PORT runs hostname/id on the real VPS."
step "Reboot only after all checks pass; then repeat the SSH and dashboard checks before deleting the backup."
warn "Rollback data is in $BACKUP_DIR. Restore .env first and redeploy Fyke before restoring any public OpenSSH listener, so two services never compete for the same address and port."
confirm "Did every public/private verification pass?" || die "keep both SSH shells open and roll back using $BACKUP_DIR"

finish
say "Real SSH:  ssh -p $ADMIN_TAILNET_PORT $FYKE_ADMIN_USER@$FYKE_TAILNET_HOST"
say "Dashboard: https://$FYKE_TAILNET_HOST/"
say "Backup:    $BACKUP_DIR"
