#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"
ENV_FILE="$REPO_DIR/.env"
ADMIN_TAILNET_PORT=22222
SSH_DROPIN=/etc/ssh/sshd_config.d/00-fyke-loopback.conf
BACKUP_DIR=""

setup_banner() {
  _clear
  printf '\n%s%s  Put Fyke on the public ports%s\n' "$BOLD" "$BLUE" "$RESET"
  printf '%s  %s steps%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  say "This script moves the fake services to ports 22, 23, 80, and 443."
  say "It keeps real SSH and the dashboard inside your tailnet."
  warn "Keep your current SSH window open during all steps."
  pause "Press Enter to start."
}

open_setup_url() {
  local url="$1"
  say "Open this address in a browser: $url"
}

save_setting() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
  say "Saved $key in $ENV_FILE."
}

setup_finish() {
  _clear
  printf '\n%s%s  Setup is complete.%s\n\n' "$BOLD" "$GREEN" "$RESET"
}

as_root() {
  if (( EUID == 0 )); then
    "$@"
  else
    sudo "$@"
  fi
}

die() {
  printf '\n  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

valid_ipv4() {
  local address="$1" octet
  local -a octets
  [[ "$address" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  IFS=. read -r -a octets <<<"$address"
  for octet in "${octets[@]}"; do
    (( 10#$octet <= 255 )) || return 1
  done
}

reload_ssh_listener() {
  as_root systemctl daemon-reload
  if as_root systemctl is-active --quiet ssh.socket || as_root systemctl is-enabled --quiet ssh.socket; then
    as_root systemctl restart ssh.socket
  else
    as_root systemctl reload ssh.service
  fi
}

loopback_ssh_only() {
  local address endpoint listeners port sshd_effective
  local saw_ipv4=0 saw_ipv6=0

  sshd_effective=$(as_root /usr/sbin/sshd -T) || return 1
  while IFS= read -r port; do
    [[ "$port" == 22 ]] || return 1
  done < <(awk '$1 == "port" {print $2}' <<<"$sshd_effective")
  while IFS= read -r address; do
    case "$address" in
      127.0.0.1:22) saw_ipv4=1 ;;
      '[::1]:22') saw_ipv6=1 ;;
      *) return 1 ;;
    esac
  done < <(awk '$1 == "listenaddress" {print $2}' <<<"$sshd_effective")
  (( saw_ipv4 == 1 && saw_ipv6 == 1 )) || return 1

  listeners=$(as_root ss -H -ltn 'sport = :22')
  [[ -n "$listeners" ]] || return 1
  while IFS= read -r line; do
    endpoint=$(awk '{print $4}' <<<"$line")
    case "$endpoint" in
      127.0.0.1:22|'[::1]:22') ;;
      *) return 1 ;;
    esac
  done <<<"$listeners"
}

restore_ssh_dropin() {
  if [[ -f "$BACKUP_DIR/ssh-dropin.before" ]]; then
    as_root install -o root -g root -m 600 "$BACKUP_DIR/ssh-dropin.before" "$SSH_DROPIN"
  else
    as_root rm -f "$SSH_DROPIN"
  fi
  as_root /usr/sbin/sshd -t
  reload_ssh_listener
}

if [[ "${FYKE_GO_LIVE_FUNCTIONS_ONLY:-0}" == 1 ]]; then
  return 0 2>/dev/null || exit 0
fi

setup_banner

stage "Check this server"
say "Run this script on the VPS that will run Fyke."
warn "Keep this SSH window open. Open your provider console before you continue."
for command in docker tailscale ip ss ssh curl systemctl; do
  command -v "$command" >/dev/null 2>&1 || die "Install $command, and then run this script again."
done
if (( EUID != 0 )); then
  command -v sudo >/dev/null 2>&1 || die "Install sudo, and then run this script again."
fi
[[ -x /usr/sbin/sshd ]] || die "Install the OpenSSH server, and then run this script again."
docker info >/dev/null 2>&1 || die "Docker is not running, or your user cannot use Docker."
as_root true || die "Run this script as root or as a user that can use sudo."
as_root tailscale status >/dev/null 2>&1 || die "Connect this VPS to Tailscale, and then run this script again."
if [[ -z "${SSH_CONNECTION:-}" ]]; then
  warn "This does not look like an SSH session. Keep your provider console open."
fi
say "This VPS has these IPv4 addresses:"
ip -4 -brief address show scope global | sed 's/^/    /'
ask FYKE_BIND_IP "Type the IPv4 address that receives public internet traffic:"
valid_ipv4 "$FYKE_BIND_IP" || die "Type a valid IPv4 address."
ip -4 address show | grep -Fqw "$FYKE_BIND_IP" || die "$FYKE_BIND_IP is not an address on this VPS. Do not use a cloud NAT address."
[[ "$FYKE_BIND_IP" != 0.0.0.0 && "$FYKE_BIND_IP" != 127.0.0.1 ]] || die "Type the public interface address. Do not use 0.0.0.0 or 127.0.0.1."
ask FYKE_ADMIN_USER "Type the user name for real SSH. Press Enter to use $(id -un):"
FYKE_ADMIN_USER="${FYKE_ADMIN_USER:-$(id -un)}"
tailnet_self=$(as_root tailscale status --self=true --peers=false --json 2>/dev/null) || die "Fyke cannot read the Tailscale status for this VPS."
FYKE_TAILNET_HOST=$(sed -n 's/.*"DNSName":[[:space:]]*"\([^"]*\)".*/\1/p' <<<"$tailnet_self" | head -n1)
FYKE_TAILNET_HOST="${FYKE_TAILNET_HOST%.}"
[[ -n "$FYKE_TAILNET_HOST" ]] || die "Tailscale did not give this VPS a MagicDNS name. Enable MagicDNS, and then try again."
[[ "$FYKE_TAILNET_HOST" != *[[:space:]/:]* ]] || die "Tailscale returned a MagicDNS name that Fyke cannot use."
say "Tailscale name: $FYKE_TAILNET_HOST"
say "Use a user email address or a group name such as group:admins."
ask TAILSCALE_ADMIN_PRINCIPAL "Type the Tailscale user or group that can manage this VPS:"
[[ -n "$TAILSCALE_ADMIN_PRINCIPAL" ]] || die "Type one Tailscale user or group."
note "This script does not ask for a password, an SSH key, or a Tailscale key."
pause "Check the values above. Press Enter to continue."

stage "Save a backup"
say "Use this backup if you must undo the changes."
say "Fyke will save these items:"
step "The OpenSSH settings."
step "The Fyke .env file, if it exists."
step "The Tailscale Serve settings."
say "Only the root user can read the backup."
confirm "Create the backup and continue?" || die "The script stopped. It did not change any settings."
BACKUP_DIR="/var/backups/fyke-public-setup-$(date -u +%Y%m%dT%H%M%SZ)"
as_root install -d -o root -g root -m 700 "$BACKUP_DIR"
as_root cp -a /etc/ssh/sshd_config "$BACKUP_DIR/sshd_config"
as_root cp -a /etc/ssh/sshd_config.d "$BACKUP_DIR/sshd_config.d"
if as_root test -f "$SSH_DROPIN"; then
  as_root cp -a "$SSH_DROPIN" "$BACKUP_DIR/ssh-dropin.before"
fi
if [[ -f "$ENV_FILE" ]]; then
  as_root cp -a "$ENV_FILE" "$BACKUP_DIR/fyke.env.before"
fi
status_file=$(mktemp)
as_root tailscale serve status --json >"$status_file" 2>/dev/null || as_root tailscale serve status >"$status_file"
as_root install -o root -g root -m 600 "$status_file" "$BACKUP_DIR/tailscale-serve.before"
rm -f "$status_file"
services_file=$(mktemp)
systemctl is-active ssh.service ssh.socket tailscaled.service >"$services_file" 2>&1 || true
as_root install -o root -g root -m 600 "$services_file" "$BACKUP_DIR/services.before"
rm -f "$services_file"
say "Backup folder: $BACKUP_DIR"
warn "Keep this backup until you restart the VPS and test real SSH and the dashboard."
pause "The backup is complete. Press Enter to continue."

stage "Limit Tailscale access"
TAILSCALE_IP=$(as_root tailscale ip -4 | head -n1)
say "A grant is a Tailscale access rule."
say "The new grant lets the selected user or group use real SSH and the dashboard."
warn "An old rule can still give access to other users. Check all rules for this VPS."
open_setup_url "https://login.tailscale.com/admin/acls"
step "Add this grant to the current policy. Keep all unrelated rules."
printf '\n    {\n      "src": ["%s"],\n      "dst": ["%s"],\n      "ip": ["tcp:%s", "tcp:443"]\n    }\n\n' \
  "$TAILSCALE_ADMIN_PRINCIPAL" "$TAILSCALE_IP" "$ADMIN_TAILNET_PORT"
step "Find other rules that give access to this VPS on these ports. Remove access that is not needed."
step "Run the policy tests."
step "Save the policy."
confirm "Did you save the policy, and did its tests pass?" || die "The script stopped before it created the Tailscale connections."

stage "Create private access"
say "Tailscale will send port $ADMIN_TAILNET_PORT to real OpenSSH on this VPS."
say "Tailscale will also give the dashboard a private HTTPS address."
confirm "Create both Tailscale connections?" || die "The script stopped. It did not change Tailscale Serve."
as_root tailscale serve --bg --tcp="$ADMIN_TAILNET_PORT" tcp://127.0.0.1:22
as_root tailscale serve --bg --https=443 http://127.0.0.1:9080
as_root tailscale serve status
curl -fsS http://127.0.0.1:9080/api/v1/health >/dev/null || die "The Fyke dashboard does not respond on this VPS."
pause "The private connections are ready. Press Enter to test them."

stage "Test private access"
warn "Do not continue until both tests pass."
say "On a different device in your tailnet, run this command:"
printf '\n    ssh -p %s %s@%s\n\n' "$ADMIN_TAILNET_PORT" "$FYKE_ADMIN_USER" "$FYKE_TAILNET_HOST"
say "In the new SSH window, run hostname and id. These commands must show the real VPS."
say "On the same device, open this address in a browser:"
printf '\n    https://%s/\n\n' "$FYKE_TAILNET_HOST"
step "Keep the original SSH window open."
step "Keep the new SSH window open."
confirm "Can you use real SSH and open the dashboard?" || die "The script stopped. Public OpenSSH did not change."

stage "Make real SSH private"
say "A loopback address is available only inside this VPS."
say "This step moves real OpenSSH to loopback port 22."
say "Tailscale port $ADMIN_TAILNET_PORT will remain the remote connection."
warn "The script will restore the old settings if an automatic test fails."
say "The current OpenSSH network settings are:"
as_root grep -RHE '^[[:space:]]*(Port|ListenAddress)[[:space:]]' /etc/ssh/sshd_config /etc/ssh/sshd_config.d 2>/dev/null | sed 's/^/    /' || true
confirm "Move real OpenSSH to the loopback addresses now?" || die "The script stopped. It did not change OpenSSH."
ssh_dropin_tmp=$(mktemp)
printf '%s\n' \
  '# Managed by Fyke scripts/go-live.sh.' \
  'Port 22' \
  'ListenAddress 127.0.0.1:22' \
  'ListenAddress [::1]:22' >"$ssh_dropin_tmp"
as_root install -o root -g root -m 600 "$ssh_dropin_tmp" "$SSH_DROPIN"
rm -f "$ssh_dropin_tmp"
if ! as_root /usr/sbin/sshd -t; then
  restore_ssh_dropin
  die "OpenSSH rejected the new settings. Fyke restored the old settings."
fi
if ! reload_ssh_listener; then
  warn "OpenSSH could not start with the new settings. Fyke will restore the old settings."
  restore_ssh_dropin || true
  die "Fyke tried to restore OpenSSH. Use the provider console if SSH does not work."
fi
if ! loopback_ssh_only; then
  warn "Real SSH still has a non-loopback address. Fyke will restore the old settings."
  restore_ssh_dropin
  die "Check all Port and ListenAddress lines in the OpenSSH settings."
fi
as_root ss -ltnp 'sport = :22' || true
warn "Use the second SSH window. Test Tailscale port $ADMIN_TAILNET_PORT again."
confirm "Does real SSH still work on Tailscale port $ADMIN_TAILNET_PORT?" || {
  restore_ssh_dropin
  die "Fyke restored the old OpenSSH settings."
}

stage "Remove the old Tailscale access"
say "The new Tailscale connections now work."
say "This step turns off Tailscale SSH on port 22."
say "It also removes the old dashboard address on port 9080."
confirm "Remove both old Tailscale connections?" || die "The script stopped. The new private connections still work."
as_root tailscale set --ssh=false
if ! as_root tailscale serve --http=9080 off; then
  warn "Fyke did not find the old dashboard connection on port 9080. Check the Tailscale Serve status."
fi
as_root tailscale serve status
warn "Test real SSH and the dashboard again."
confirm "Do real SSH and the dashboard still work?" || die "Stop now. Use the backup in $BACKUP_DIR to restore the old settings."

stage "Start Fyke on the public ports"
say "Fyke will use only the selected public IPv4 address."
say "Fyke will not use the Tailscale or loopback addresses."
printf '  Public IPv4 address: %s\n  Public Fyke ports:   22, 23, 80, 443\n' "$FYKE_BIND_IP"
confirm "Save these ports and restart the Fyke services?" || die "The script stopped before it opened the public ports."
save_setting FYKE_BIND_IP "$FYKE_BIND_IP"
save_setting FYKE_SSH_PORT 22
save_setting FYKE_TELNET_PORT 23
save_setting FYKE_HTTP_PORT 80
save_setting FYKE_HTTPS_PORT 443
./deploy.sh
docker compose ps
pause "Fyke is running on the public ports. Press Enter to set the firewall rules."

stage "Set the firewall rules"
say "The Fyke firewall rule blocks connections from a sensor to other networks."
say "The rule still lets each sensor send data to the Fyke controller."
./deploy.sh firewall
confirm "Install the firewall rule shown above?" || die "The script stopped. Fyke is running, but its sensor firewall rule is not installed."
./deploy.sh firewall apply
ask CLOUD_FIREWALL_URL "Type the cloud firewall page address. Press Enter to skip this step:"
if [[ -n "$CLOUD_FIREWALL_URL" ]]; then
  open_setup_url "$CLOUD_FIREWALL_URL"
fi
step "Allow inbound TCP ports 22, 23, 80, and 443 from the public internet."
step "Block public TCP ports 2222, 2323, 8080, 8443, 9080, and $ADMIN_TAILNET_PORT."
step "Keep the current Tailscale rules."
step "Keep established traffic and outbound traffic enabled."
warn "Fyke does not listen on public IPv6. Keep public IPv6 input blocked."
confirm "Did you save the cloud firewall rules and keep Tailscale working?" || die "Check the cloud firewall before you close this SSH window."

stage "Test the finished setup"
say "Use a device that is not in your tailnet. Run these tests:"
printf '\n    ssh -p 22 deploy@%s\n    curl -i http://%s/\n    curl -ki https://%s/\n\n' \
  "$FYKE_BIND_IP" "$FYKE_BIND_IP" "$FYKE_BIND_IP"
say "Use an allowed device in your tailnet. Run these tests:"
printf '\n    ssh -p %s %s@%s\n    https://%s/\n\n' \
  "$ADMIN_TAILNET_PORT" "$FYKE_ADMIN_USER" "$FYKE_TAILNET_HOST" "$FYKE_TAILNET_HOST"
step "Check that public ports 9080 and $ADMIN_TAILNET_PORT do not connect."
step "Check that public port 22 shows the Fyke SSH service."
step "Check that Tailscale port $ADMIN_TAILNET_PORT opens the real VPS."
warn "Do not restart the VPS until all tests pass."
warn "If you restore the backup, restore .env and restart Fyke first. Then restore OpenSSH."
say "Backup folder: $BACKUP_DIR"
confirm "Did all public and private tests pass?" || die "Keep both SSH windows open. Use the backup to restore the old settings."

setup_finish
say "Real SSH command: ssh -p $ADMIN_TAILNET_PORT $FYKE_ADMIN_USER@$FYKE_TAILNET_HOST"
say "Dashboard address: https://$FYKE_TAILNET_HOST/"
say "Backup folder: $BACKUP_DIR"
